services:
  frontend:
    build:
      context: .
      dockerfile: ./taxi-frontend/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./taxi-backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
